### ISSUE TITLE
The [path] value in allow & disallow directives must start with "/"

### ISSUE THREAD

**Issue by ycherniavskyi** [superwolff/metalsmith-robots#3]
Settings `public: true` or `private: true` in a file's frontmatter add that page to the allow or disallow option without slash "/" in the beginning. Which lead to incorrect interpretation of its value by different crawler.

In Goolge [Robots.txt Specifications](https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt) you can find rule that [path] must start with "/".
Also with Yandex [Robots.txt analysis](https://webmaster.yandex.ru/tools/robotstxt/?ncrnd=1463) you can check that without "/" it marks such rule as error - "Rule doesn't start with / or *".

**Comment by emmercm** [comment]
I don't think this is fixed @ismay @woodyrew.
